# Generated by Django 5.2.5 on 2025-10-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangarinorg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Priority', 'verbose_name_plural': 'Priorities'},
        ),
    ]
